#!/usr/bin/env node

/**
 * Setup Script for Movie Search App
 * Helps users configure their environment variables
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';
import process from 'process';

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🎬 Movie Search App - Environment Setup');
console.log('======================================\n');

// Check if .env.local already exists
const envPath = path.join(process.cwd(), '.env.local');

if (fs.existsSync(envPath)) {
  console.log('✅ .env.local file already exists!');
  console.log('🔍 Current configuration:');
  
  try {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const hasApiKey = envContent.includes('VITE_OMDB_API_KEY=') && 
                     !envContent.includes('your_api_key_here');
    
    if (hasApiKey) {
      console.log('✅ API key is configured');
    } else {
      console.log('❌ API key is missing or not configured');
    }
  } catch {
    console.log('❌ Error reading .env.local file');
  }
  
  rl.question('\nDo you want to reconfigure? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      setupEnvironment();
    } else {
      console.log('\n🚀 Setup complete! Run "npm run dev" to start the app.');
      rl.close();
    }
  });
} else {
  setupEnvironment();
}

function setupEnvironment() {
  console.log('\n📝 Let\'s set up your environment variables...\n');
  
  console.log('🔑 You need an OMDB API key:');
  console.log('   1. Visit: http://www.omdbapi.com/apikey.aspx');
  console.log('   2. Register for a FREE API key');
  console.log('   3. Enter your API key below\n');
  
  rl.question('Enter your OMDB API key: ', (apiKey) => {
    if (!apiKey || apiKey.trim().length === 0) {
      console.log('❌ API key is required! Please run the setup again.');
      rl.close();
      return;
    }
    
    // Create .env.local content
    const envContent = `# Environment Variables for Movie Search App
# Generated by setup script on ${new Date().toISOString()}

# OMDB API Key - Get yours from http://www.omdbapi.com/apikey.aspx
VITE_OMDB_API_KEY=${apiKey.trim()}

# Note: This file should never be committed to version control
# It's already included in .gitignore for your security
`;
    
    try {
      fs.writeFileSync(envPath, envContent, 'utf8');
      console.log('\n✅ Environment configured successfully!');
      console.log('📁 Created: .env.local');
      console.log('🔒 Your API key is secure and will not be committed to Git');
      console.log('\n🚀 Next steps:');
      console.log('   1. Run: npm run dev');
      console.log('   2. Open: http://localhost:5173');
      console.log('   3. Start searching for movies! 🎬\n');
    } catch (writeError) {
      console.log('❌ Error creating .env.local file:', writeError.message);
    }
    
    rl.close();
  });
}

// Handle Ctrl+C gracefully
rl.on('SIGINT', () => {
  console.log('\n\n👋 Setup cancelled. Run "npm run setup" to try again.');
  process.exit(0);
});